export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const GET_LIVE_NOTESHEETS = "GET_LIVE_NOTESHEETS";
export const USER_NOTESHEETS = "USER_NOTESHEETS";
export const CREATE_NOTESHEET = "CREATE_NOTESHEET";
export const UPDATE_NOTESHEET = "UPDATE_NOTESHEET";
export const NOTESHEETS_ERROR = "NOTESHEETS_ERROR";
export const REMOVE_NOTESHEETS = "REMOVE_NOTESHEETS";

export const SET_ALERT = "SET_ALERT";
